# Generated by Django 5.1.1 on 2024-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnigmasHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigma',
            name='answers',
            field=models.IntegerField(default=0),
        ),
    ]
